name: Deployment

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: volleyball-stat-tracker-app

    steps:
      - run: ls
      - run: echo deployingTest
