name: Deployment

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: react-build-folder

      - name: Display structure of downloaded files
        run: ls -R

      - name: Display downloaded files
        run: ls
