name: Deployment

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: react-build-folder

      - name: Display structure of downloaded files
        run: ls -R

      - name: Upload react build artifact to S3 Bucket
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_KEY}}
          aws_bucket: ${{ secrets.VOLLEYLOG_S3_BUCKET }}
          source_dir: "./"
