name: Deployment

on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY:
        description: "AWS Access Key"
        required: true
      AWS_SECRET_KEY:
        description: "AWS Access Secret Key"
        required: true
      VOLLEYLOG_S3_BUCKET:
        description: "Volleylog S3 Bucket name"
        required: true
      VOLLEYLOG_CLOUDFRONT_ID:
        description: "Volleylog Cloudfront distribution ID"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Create build folder
        run: mkdir build

      - name: Download react build artifacts to build folder
        uses: actions/download-artifact@v3
        with:
          name: react-build-folder
          path: build

      - name: Upload react build artifact to S3 Bucket
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{secrets.AWS_ACCESS_KEY}}
          aws_secret_access_key: ${{secrets.AWS_SECRET_KEY}}
          aws_bucket: ${{secrets.VOLLEYLOG_S3_BUCKET}}
          source_dir: "build"
          destination_dir: ""

      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{secrets.VOLLEYLOG_CLOUDFRONT_ID}}
          PATHS: "/index.html"
          AWS_REGION: "us-east-1"
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_KEY}}
