name: Deployment

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: volleyball-stat-tracker-app

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: react-build-folder

      - name: Display structure of downloaded files
        run: ls -R
