name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    name: Build Volleylog web app
    uses: ./.github/workflows/build.yml

  deploy:
    name: Deploy Volleylog web app
    needs: build
    uses: ./.github/workflows/deploy.yml
    with:
      environment: production
    secrets:
      AWS_ACCESS_KEY: ${{secrets.AWS_ACCESS_KEY}}
      AWS_SECRET_KEY: ${{secrets.AWS_SECRET_KEY}}
      VOLLEYLOG_S3_BUCKET: ${{secrets.VOLLEYLOG_S3_BUCKET}}
      VOLLEYLOG_CLOUDFRONT_ID: ${{secrets.VOLLEYLOG_CLOUDFRONT_ID}}
