name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml

  deploy_test:
    uses: ./.github/workflows/deploy.yml
