name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    uses: Angelo4/Volleyball-Stat-Tracker/.github/workflows/build.yml@main
    with:
      nodeVersion: 16

  deploy_test:
    uses: Angelo4/Volleyball-Stat-Tracker/.github/workflows/deploy.yml@main
